# Generated by Django 3.0.2 on 2020-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200113_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
