# Generated by Django 3.0.2 on 2020-01-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_biographie'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
