# Generated by Django 3.0.2 on 2020-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200113_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
