# Generated by Django 3.0.2 on 2020-02-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_remove_role_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
