# Generated by Django 3.0.2 on 2020-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20200203_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'Stadt'), (2, 'Aktive Wehr'), (3, 'Jugendfeuerwehr'), (4, 'Unterstützungseinheit'), (5, 'Alter und Ehrenabteilung')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Leiter der Feuerwehr'), (2, 'Stadtjugendwart'), (3, 'Einheitsführung'), (4, 'Jugendwart'), (5, 'Betreuerteam')], max_length=30, null=True),
        ),
    ]
