# Generated by Django 3.0.2 on 2020-01-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200109_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='place',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='postcode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
