# Generated by Django 3.0.2 on 2020-01-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200109_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='housenumber',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
