# Generated by Django 3.0.2 on 2020-01-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200109_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
