# Generated by Django 2.2.4 on 2020-01-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_unit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
