# Generated by Django 3.0.2 on 2020-01-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20200111_1825'),
        ('events', '0007_auto_20200110_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Kindtable'),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit'),
        ),
    ]
