# Generated by Django 3.0.2 on 2020-01-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_forall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='forall',
        ),
    ]
