# Generated by Django 3.0.2 on 2020-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_forall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindtable',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
