# Generated by Django 3.0.2 on 2020-01-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200117_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindtable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
