# Generated by Django 3.0.2 on 2020-01-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_kindtable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindtable',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
