# Generated by Django 3.0.2 on 2020-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecontent',
            name='context',
            field=models.TextField(),
        ),
    ]
