# Generated by Django 3.0.2 on 2020-01-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200117_1943'),
        ('knowledges', '0003_fwdv_fwdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('ordernumber', models.IntegerField(unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledgecontent',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='fwdv',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='slug',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='footer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Fwdv',
        ),
        migrations.DeleteModel(
            name='Knowledgecontent',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledges.Topic'),
            preserve_default=False,
        ),
    ]
