# Generated by Django 3.0.2 on 2020-01-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('housenumber', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=256)),
                ('place', models.CharField(max_length=256)),
            ],
        ),
    ]
