# Generated by Django 2.2.4 on 2020-01-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
