# Generated by Django 2.2.4 on 2020-01-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20200110_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='time',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='unit',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
