# Generated by Django 3.0.2 on 2020-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20200110_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
