# Generated by Django 3.0.2 on 2020-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20200111_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
