# Generated by Django 3.0.2 on 2020-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20200111_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='a_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='a_endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='a_starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
