# Generated by Django 3.0.2 on 2020-01-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_workinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.CharField(blank=True, choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Samstag'), ('SO', 'Sonntag')], max_length=15, null=True),
        ),
    ]
