# Generated by Django 3.0.2 on 2020-01-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_auto_20200127_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='a_day',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='a_endtime',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='a_starttime',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='day',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='starttime',
        ),
    ]
