# Generated by Django 3.0.2 on 2020-01-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20200127_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
