# Generated by Django 3.0.2 on 2020-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_unit_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
