# Generated by Django 3.0.2 on 2020-02-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_unit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='wallpaper',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
