# Generated by Django 2.2.4 on 2020-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('published', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=256)),
            ],
        ),
    ]
