# Generated by Django 3.0.2 on 2020-01-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20200118_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
