# Generated by Django 3.0.2 on 2020-02-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200204_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='updated',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
