# Generated by Django 3.0.2 on 2020-02-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_filedocument_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='document',
            field=models.FileField(max_length=254, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
