# Generated by Django 3.0.2 on 2020-02-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200205_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='published',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
