# Generated by Django 3.0.2 on 2020-01-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegroup',
            name='shortcut',
            field=models.CharField(default='RW', max_length=256),
            preserve_default=False,
        ),
    ]
