# Generated by Django 3.0.2 on 2020-01-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_vehiclegroup_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='construction_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
